[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors=["Magnus Stuart Juul, <magnus.s.juul@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
chrono="0.4"